# Generated by Django 2.1 on 2018-09-21 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'Профнастил'), (2, 'Металлочерепица'), (3, 'Мансардное окно')], default=1)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'НС'), (2, 'ПК'), (3, 'Н')], default=1)),
                ('height', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('height', models.DecimalField(decimal_places=2, help_text='толщина металла', max_digits=3)),
                ('surface', models.PositiveIntegerField(choices=[(1, 'Цинк'), (2, '3D Декоративный'), (3, 'Полиестер матовый PEMA'), (4, 'Полиестер PE')], help_text='тип покрытия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priceapi.CommonInfo')),
            ],
            options={
                'verbose_name': 'Свойства',
                'verbose_name_plural': 'Свойства',
            },
        ),
    ]
