language: python
python:
  - "3.5"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE dev;'

install:
  - pip install -r requirements-test.txt
script:
  - ./src/manage.py test priceapi