version: '3.3'

services:
    db:
        image: mysql:latest
        env_file:
          - ./common.env
        ports:
          - 3306:3306
#        hostname: 127.0.0.1

#        socket: /var/run/mysqld/mysqld.sock #just comment it out
#        volumes:
#          - /dbdata:/usr/sbin/mysqld
